paginate_number:
  per_page: 10
film:
  describe_maximum: 450
  describe_minimum: 250
user:
  name_maximum: 50
  email_maximum: 255
  password_minimum: 6
  expire_hours: 2
rating:
  review_maximum: 450
post:
  describe_maximum: 50
